# Generated by Django 5.0.7 on 2026-06-17 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('industry', models.CharField(choices=[('ai_ml', 'Artificial Intelligence / ML'), ('fintech', 'Fintech'), ('healthtech', 'Healthtech'), ('edtech', 'Edtech'), ('saas', 'SaaS / Cloud'), ('ecommerce', 'E-commerce'), ('marketplace', 'Marketplace'), ('social', 'Social Media'), ('gaming', 'Gaming'), ('cleantech', 'Cleantech'), ('biotech', 'Biotech'), ('blockchain', 'Blockchain / Web3'), ('real_estate', 'Real Estate / PropTech'), ('transport', 'Transport / Mobility'), ('food_tech', 'Food Tech'), ('travel', 'Travel / Hospitality'), ('cybersecurity', 'Cybersecurity'), ('iot', 'IoT / Hardware'), ('media', 'Media / Entertainment'), ('other', 'Other')], db_index=True, max_length=50)),
                ('stage', models.CharField(choices=[('idea', 'Idea / Concept'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+'), ('growth', 'Growth Stage')], db_index=True, max_length=50)),
                ('business_model', models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('b2b2c', 'B2B2C'), ('marketplace', 'Marketplace'), ('subscription', 'Subscription'), ('freemium', 'Freemium'), ('advertising', 'Advertising'), ('hardware', 'Hardware'), ('other', 'Other')], default='', max_length=50)),
                ('funding_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='startups/logos/')),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='startups/pitch_decks/')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='startups/verification/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'db_table': 'startups_startup',
            },
        ),
        migrations.CreateModel(
            name='StartupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='startups/documents/')),
                ('document_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('financial_model', 'Financial Model'), ('market_analysis', 'Market Analysis'), ('term_sheet', 'Term Sheet'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='startups.startup')),
            ],
            options={
                'db_table': 'startups_document',
            },
        ),
        migrations.CreateModel(
            name='StartupFundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('investors', models.TextField(blank=True, default='')),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='startups.startup')),
            ],
            options={
                'db_table': 'startups_funding_round',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StartupMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_active_users', models.PositiveIntegerField(blank=True, null=True)),
                ('total_users', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('burn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('runway_months', models.PositiveIntegerField(blank=True, null=True)),
                ('traction_description', models.TextField(blank=True, default='')),
                ('key_achievements', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Startup Metric',
                'verbose_name_plural': 'Startup Metrics',
                'db_table': 'startups_metric',
            },
        ),
        migrations.CreateModel(
            name='StartupSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('crunchbase', 'Crunchbase'), ('angel_list', 'AngelList / Wellfound'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('product_hunt', 'Product Hunt'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='startups.startup')),
            ],
            options={
                'db_table': 'startups_social_link',
            },
        ),
        migrations.CreateModel(
            name='StartupTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='startups/team/')),
                ('bio', models.TextField(blank=True, default='')),
                ('is_founder', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='startups.startup')),
            ],
            options={
                'db_table': 'startups_team_member',
                'ordering': ['order', 'is_founder', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry', 'stage'], name='startups_st_industr_0ae64a_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['status', 'is_visible'], name='startups_st_status_23427c_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['-created_at'], name='startups_st_created_f2d675_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['-view_count'], name='startups_st_view_co_fd0e0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startupsociallink',
            unique_together={('startup', 'platform')},
        ),
    ]
