# Generated by Django 5.0.7 on 2026-06-18 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='detailed_pitch',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startup',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startup',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['owner', 'status'], name='startups_st_owner_i_e4bb11_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['slug'], name='startups_st_slug_32b99b_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry', 'status', 'is_visible'], name='startups_st_industr_2d0053_idx'),
        ),
    ]
