# Generated by Django 5.0.7 on 2026-06-18 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_detailed_pitch_startup_gallery_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupdocument',
            name='file',
            field=models.FileField(upload_to='startups/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'md', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
