# Generated by Django 5.0.7 on 2026-06-26 18:32

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startupdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='startups/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), apps.common.validators.ValidateFileSize(max_mb=5)]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='startups/pitch_decks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'md']), apps.common.validators.ValidateFileSize(max_mb=50)]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='startups/verification/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'md']), apps.common.validators.ValidateFileSize(max_mb=50)]),
        ),
        migrations.AlterField(
            model_name='startupteammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='startups/team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), apps.common.validators.ValidateFileSize(max_mb=5)]),
        ),
    ]
