# Generated by Django 5.0.7 on 2026-06-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_alter_startupdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('equity_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('proposed_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('due_diligence', 'Due Diligence'), ('negotiating', 'Negotiating'), ('term_sheet_sent', 'Term Sheet Sent'), ('invested', 'Invested'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='interested', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('term_sheet_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_opportunities', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_opportunities', to='startups.startup')),
            ],
            options={
                'db_table': 'investments_opportunity',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_activities', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='investments.investmentopportunity')),
            ],
            options={
                'db_table': 'investments_activity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='investmentopportunity',
            index=models.Index(fields=['investor', 'status'], name='investments_investo_16a6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentopportunity',
            index=models.Index(fields=['startup', 'status'], name='investments_startup_219577_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentopportunity',
            index=models.Index(fields=['investor', '-created_at'], name='investments_investo_9aec16_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentopportunity',
            index=models.Index(fields=['startup', '-created_at'], name='investments_startup_67f530_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentopportunity',
            index=models.Index(fields=['status', '-updated_at'], name='investments_status_03a956_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentopportunity',
            unique_together={('startup', 'investor')},
        ),
        migrations.AddIndex(
            model_name='investmentactivity',
            index=models.Index(fields=['opportunity', '-timestamp'], name='investments_opportu_b6422c_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentactivity',
            index=models.Index(fields=['actor', '-timestamp'], name='investments_actor_i_084cf7_idx'),
        ),
    ]
