# Generated by Django 5.0.7 on 2026-06-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('funding_stage', models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+'), ('growth', 'Growth')], default='', max_length=50)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepreneur Profile',
                'db_table': 'accounts_entrepreneur_profile',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_type', models.CharField(blank=True, choices=[('angel', 'Angel Investor'), ('vc', 'Venture Capital'), ('corporate', 'Corporate VC'), ('accelerator', 'Accelerator'), ('family_office', 'Family Office'), ('fund', 'Investment Fund')], default='', max_length=50)),
                ('investment_focus', models.TextField(blank=True, default='')),
                ('preferred_stage', models.CharField(blank=True, choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+')], default='', max_length=50)),
                ('ticket_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ticket_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('industries_of_interest', models.TextField(blank=True, default='')),
                ('portfolio_count', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'db_table': 'accounts_investor_profile',
            },
        ),
    ]
