# Generated by Django 5.0.7 on 2026-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entrepreneurprofile_investorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='entrepreneurprofile',
            index=models.Index(fields=['is_public', 'industry'], name='accounts_en_is_publ_09ce6e_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepreneurprofile',
            index=models.Index(fields=['funding_stage'], name='accounts_en_funding_12362a_idx'),
        ),
    ]
