# Generated by Django 5.0.7 on 2026-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entrepreneurprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='follow_on_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investments_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='lead_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='portfolio_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_geographies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_industries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_stages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['is_public', 'investor_type'], name='accounts_in_is_publ_adfd63_idx'),
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['city', 'country'], name='accounts_in_city_a5aee6_idx'),
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['years_of_experience'], name='accounts_in_years_o_3095a1_idx'),
        ),
    ]
