# Generated by Django 5.0.7 on 2026-06-26 18:32

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_investorprofile_bio_investorprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'md']), apps.common.validators.ValidateFileSize(max_mb=50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), apps.common.validators.ValidateFileSize(max_mb=5)]),
        ),
    ]
