# Generated by Django 5.0.7 on 2026-06-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0003_alter_interactionevent_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='matching.matchscore')),
            ],
            options={
                'db_table': 'match_intelligence_insight',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='matching.matchscore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_intelligence_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'rating'], name='match_intel_match_i_c42c19_idx'), models.Index(fields=['user', '-created_at'], name='match_intel_user_id_b0ae7c_idx')],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
