# Generated by Django 5.0.7 on 2026-06-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_alter_startupdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('matched_investors', 'Matched Investors'), ('selected_investors', 'Selected Investors')], default='matched_investors', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_data_rooms', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rooms', to='startups.startup')),
            ],
            options={
                'db_table': 'data_room_room',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_room/documents/')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('financials', 'Financials'), ('cap_table', 'Cap Table'), ('business_plan', 'Business Plan'), ('legal', 'Legal'), ('traction_report', 'Traction Report'), ('product_demo', 'Product Demo'), ('market_research', 'Market Research'), ('other', 'Other')], default='other', max_length=25)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data_room.dataroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_room_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='data_room.dataroomdocument')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_document_access', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_room_document_access',
            },
        ),
        migrations.CreateModel(
            name='DocumentViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='data_room.dataroomdocument')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_room_document_view',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataroom',
            index=models.Index(fields=['startup', 'visibility'], name='data_room_r_startup_0509c5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroom',
            index=models.Index(fields=['created_by'], name='data_room_r_created_14d5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocument',
            index=models.Index(fields=['data_room', 'document_type'], name='data_room_d_data_ro_13a336_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocument',
            index=models.Index(fields=['data_room', '-created_at'], name='data_room_d_data_ro_533de3_idx'),
        ),
        migrations.AddIndex(
            model_name='dataroomdocument',
            index=models.Index(fields=['uploaded_by'], name='data_room_d_uploade_aad2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['investor', 'document'], name='data_room_d_investo_50c68e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('document', 'investor')},
        ),
        migrations.AddIndex(
            model_name='documentviewevent',
            index=models.Index(fields=['document', 'investor'], name='data_room_d_documen_543cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentviewevent',
            index=models.Index(fields=['investor', '-viewed_at'], name='data_room_d_investo_12e2e1_idx'),
        ),
    ]
