# Generated by Django 5.0.7 on 2026-06-26 18:32

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdocument',
            name='file',
            field=models.FileField(upload_to='data_room/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'md']), apps.common.validators.ValidateFileSize(max_mb=50)]),
        ),
    ]
