# Generated by Django 5.0.7 on 2026-06-18 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_type', models.CharField(choices=[('startups', 'Startups'), ('investors', 'Investors'), ('founders', 'Founders'), ('opportunities', 'Opportunities')], db_index=True, max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_saved',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'search_type'], name='search_save_user_id_b1d8bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(db_index=True, max_length=30)),
                ('result_id', models.PositiveIntegerField()),
                ('query', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_click',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_clic_user_id_88f039_idx'), models.Index(fields=['result_type', 'result_id'], name='search_clic_result__bad39d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('search_type', models.CharField(db_index=True, max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['query'], name='search_hist_query_69a772_idx')],
            },
        ),
    ]
