FROM nginx:1.26-alpine

LABEL maintainer="Investo Team"
LABEL description="Investo Nginx Reverse Proxy"

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
