# Generated by Django 5.0.7 on 2026-06-19 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(choices=[('error_rate', 'Error Rate'), ('queue_backlog', 'Queue Backlog'), ('response_time', 'Response Time'), ('db_connections', 'Database Connections'), ('ws_connections', 'WebSocket Connections'), ('cache_hit_rate', 'Cache Hit Rate'), ('storage_availability', 'Storage Availability'), ('failed_logins', 'Failed Logins')], db_index=True, max_length=30)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('eq', 'Equals')], max_length=5)),
                ('threshold', models.FloatField()),
                ('window_minutes', models.PositiveIntegerField(default=5)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_slack', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'obs_alert_rule',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='triggered', max_length=15)),
                ('metric_value', models.FloatField()),
                ('message', models.TextField(blank=True, default='')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='observability.alertrule')),
            ],
            options={
                'db_table': 'obs_alert_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('endpoint', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obs_request_metric',
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='obs_request_endpoin_6535f8_idx'), models.Index(fields=['is_error', '-created_at'], name='obs_request_is_erro_1d70cc_idx'), models.Index(fields=['-created_at'], name='obs_request_created_a4d1ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API'), ('celery', 'Celery Task'), ('websocket', 'WebSocket'), ('payment', 'Payment'), ('storage', 'Storage'), ('database', 'Database'), ('internal', 'Internal')], db_index=True, default='api', max_length=20)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=15)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obs_system_error',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'severity'], name='obs_system__source_4ec8a3_idx'), models.Index(fields=['-created_at'], name='obs_system__created_e174d4_idx')],
            },
        ),
    ]
