# Generated by Django 5.0.7 on 2026-06-17 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('preferred_stages', models.JSONField(blank=True, default=list)),
                ('min_ticket_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_ticket_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_geographies', models.JSONField(blank=True, default=list)),
                ('risk_appetite', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('investment_focus', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_investor_preference',
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('viewed', 'Startup Viewed'), ('bookmarked', 'Startup Bookmarked'), ('ignored', 'Startup Ignored'), ('contacted', 'Startup Contacted'), ('searched', 'Search Performed'), ('shared', 'Startup Shared')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='startups.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_interaction_event',
                'indexes': [models.Index(fields=['user', 'event_type'], name='matching_in_user_id_047a34_idx'), models.Index(fields=['startup', 'event_type'], name='matching_in_startup_879f16_idx'), models.Index(fields=['-created_at'], name='matching_in_created_6e389b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('bookmarked_at', models.DateTimeField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('is_ignored', models.BooleanField(default=False)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='startups.startup')),
            ],
            options={
                'db_table': 'matching_match_score',
                'indexes': [models.Index(fields=['investor', '-score'], name='matching_ma_investo_8655aa_idx'), models.Index(fields=['startup', '-score'], name='matching_ma_startup_9d7843_idx')],
                'unique_together': {('investor', 'startup')},
            },
        ),
    ]
