# Generated by Django 5.0.7 on 2026-06-18 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('startups', '0002_startup_detailed_pitch_startup_gallery_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matching_dismissed_match',
            },
        ),
        migrations.CreateModel(
            name='SavedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matching_saved_match',
            },
        ),
        migrations.AddField(
            model_name='matchscore',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('saved', 'Saved'), ('contacted', 'Contacted'), ('dismissed', 'Dismissed'), ('closed', 'Closed')], db_index=True, default='recommended', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['investor', 'status'], name='matching_ma_investo_d3bdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['startup', 'status'], name='matching_ma_startup_9b5f55_idx'),
        ),
        migrations.AddField(
            model_name='dismissedmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_by', to='matching.matchscore'),
        ),
        migrations.AddField(
            model_name='dismissedmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='matching.matchscore'),
        ),
        migrations.AddField(
            model_name='savedmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dismissedmatch',
            index=models.Index(fields=['user', '-created_at'], name='matching_di_user_id_64e8eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dismissedmatch',
            unique_together={('user', 'match')},
        ),
        migrations.AddIndex(
            model_name='savedmatch',
            index=models.Index(fields=['user', '-created_at'], name='matching_sa_user_id_795319_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedmatch',
            unique_together={('user', 'match')},
        ),
    ]
