# Generated by Django 5.0.7 on 2026-06-18 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_dismissedmatch_savedmatch_matchscore_score_breakdown_and_more'),
        ('startups', '0003_alter_startupdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactionevent',
            unique_together={('user', 'startup', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['user', '-created_at'], name='matching_in_user_id_a941b5_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['startup', '-created_at'], name='matching_in_startup_9d88f2_idx'),
        ),
    ]
