# Generated by Django 5.0.7 on 2026-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_seed_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='enabled_for_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of roles that can access this feature'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='user_percentage',
            field=models.PositiveIntegerField(default=100, help_text='Percentage of users (0-100) who see this feature'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='IPs that can bypass maintenance mode'),
        ),
        migrations.AlterField(
            model_name='maintenancemode',
            name='allowed_user_ids',
            field=models.JSONField(blank=True, default=list, help_text='User IDs that can bypass'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Exposed via public API'),
        ),
    ]
