# Generated by Django 5.0.7 on 2026-06-18 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_alter_startupdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('startup_created', 'Startup Created'), ('startup_published', 'Startup Published'), ('startup_funded', 'Startup Funded'), ('profile_updated', 'Profile Updated'), ('match_created', 'Match Created'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed'), ('investment_started', 'Investment Started'), ('investment_closed', 'Investment Closed'), ('document_uploaded', 'Document Uploaded'), ('milestone_added', 'Milestone Added'), ('investor_joined', 'Investor Joined'), ('founder_joined', 'Founder Joined')], db_index=True, max_length=25)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('connections', 'Connections'), ('private', 'Private')], default='public', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_activities', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_feed_activities', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_activities', to='startups.startup')),
            ],
            options={
                'db_table': 'activity_feed_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='activity_feed.activityfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_feed_bookmark',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activity_feed.activityfeed')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activity_feed.feedcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_feed_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('celebrate', 'Celebrate'), ('support', 'Support'), ('insightful', 'Insightful'), ('curious', 'Curious')], default='like', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='activity_feed.activityfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_feed_reaction',
            },
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['activity_type', '-created_at'], name='activity_fe_activit_d7a95a_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['actor', '-created_at'], name='activity_fe_actor_i_8d0109_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['startup', '-created_at'], name='activity_fe_startup_7ad4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['investor', '-created_at'], name='activity_fe_investo_57bc39_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['visibility', '-created_at'], name='activity_fe_visibil_7d081b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbookmark',
            unique_together={('user', 'feed_item')},
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['feed_item', '-created_at'], name='activity_fe_feed_it_9b11a8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedreaction',
            index=models.Index(fields=['feed_item', 'reaction_type'], name='activity_fe_feed_it_a899e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedreaction',
            unique_together={('user', 'feed_item', 'reaction_type')},
        ),
    ]
