# Generated by Django 5.0.7 on 2026-06-18 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_alter_startupdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meeting_type', models.CharField(choices=[('intro_call', 'Intro Call'), ('pitch_meeting', 'Pitch Meeting'), ('due_diligence', 'Due Diligence'), ('negotiation', 'Negotiation'), ('follow_up', 'Follow Up'), ('investment_committee', 'Investment Committee'), ('custom', 'Custom')], default='intro_call', max_length=25)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_meetings', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='startups.startup')),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_availability',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('note_added', 'Note Added')], max_length=25)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_events', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe')], default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_participant',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', 'status'], name='meetings_me_organiz_965dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['investor', 'status'], name='meetings_me_investo_3e53d1_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['startup', 'status'], name='meetings_me_startup_674163_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='meetings_me_schedul_ef7af7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_start'], name='meetings_me_status_535826_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingavailability',
            index=models.Index(fields=['user', 'day_of_week'], name='meetings_av_user_id_e908d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingavailability',
            unique_together={('user', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_ev_meeting_da4ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['user', 'attendance_status'], name='meetings_pa_user_id_5063ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user')},
        ),
    ]
