# Generated by Django 5.0.7 on 2026-06-18 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('matching_notifications', models.BooleanField(default=True)),
                ('investment_notifications', models.BooleanField(default=True)),
                ('chat_notifications', models.BooleanField(default=True)),
                ('document_notifications', models.BooleanField(default=True)),
                ('marketing_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f2ad08_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_f77590_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_match', 'New Match'), ('match_saved', 'Match Saved'), ('message_received', 'Message Received'), ('deal_created', 'Deal Created'), ('deal_stage_changed', 'Deal Stage Changed'), ('term_sheet_sent', 'Term Sheet Sent'), ('investment_closed', 'Investment Closed'), ('document_uploaded', 'Document Uploaded'), ('document_viewed', 'Document Viewed'), ('access_granted', 'Access Granted'), ('profile_viewed', 'Profile Viewed'), ('system', 'System')], default='system', max_length=25),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
